
services:

  nginx:
    build:
      context: .
      target: nginx
    networks:
      - all
    ports:
      - "127.0.0.1:3000:80"

  frontend-dev:
    build:
      context: .
      target: debian-src
    command: "frontend"
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - all
    volumes:
      - ./src:/opt/simple-radio/src
      # this ensures stations json file persists across restarts
      - data-public:/opt/simple-radio/public
      
  frontend-prod:
    extends:
      service: nginx
