
version: "3.9"

services:

  proxy:
    depends_on:
      - api
    build:
      context: .
      target: nginx
    networks:
     - all
    ports:
      - "8081:80"
    profiles: ["prod"]
    volumes:
      - .:/code
      - data:/data

  frontend-dev:
    build:
      context: .
      target: debian
    command: "frontend"
    depends_on:
      - api
    ports:
      - "3000:3000"
    profiles: ["dev"]
    networks:
     - all
    volumes:
      - ./src:/opt/simple-radio/src

  api:
    build:
      context: .
      target: debian
    command: "api"
    environment:
      SIMPLE_RADIO_DB: "/opt/simple-radio-data/simple_radio.db"
    networks:
     - all
    ports:
      - "8000:8000"
    volumes:
      - ./api:/opt/simple-radio/api
      - data:/opt/simple-radio-data

networks:
  all:

volumes:
  data: {}
